
### article create
POST localhost:8081/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzNDM1MzksImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyNDI5OTM5LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.XMGPa_dBm-CEtdmlwDsz-AflziH8nQrUh70_joT9rxZmbScXhnMw8yeu-phQFEhM_nlx3FO0kyyxsEOvINrGrQ
Content-Type: application/json

{
  "title": "IMPORTANT",
  "description": "IMPORTANT THINGS",
  "content": "THINGS",
  "shared_count": 2,
  "image_id": 4,
  "region_id": 1,
  "category_id": 1,
  "view_count": 4,
  "moderator_id": 1
}

### article update
PUT localhost:8081/api/v1/article/update/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzNDM1MzksImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgyNDI5OTM5LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.XMGPa_dBm-CEtdmlwDsz-AflziH8nQrUh70_joT9rxZmbScXhnMw8yeu-phQFEhM_nlx3FO0kyyxsEOvINrGrQ
Content-Type: application/json

{
  "title": "hh",
  "description": "cccc",
  "content": "ttrrr",
  "shared_count": 2,
  "image_id": 4,
  "region_id": 1,
  "category_id": 1,
  "moderator_id": 1
}