
###  upload
POST http://localhost:8081/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="vv.mp4"

< D:\photo\vv.mp4


###  upload1
POST http://localhost:8081/api/v1/attach/upload1
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="vv.mp4"

< D:\photo\vv.mp4


###  pagination
GET http://localhost:8081/api/v1/attach/pagination
Content-Type: multipart/form-data; boundary=WebAppBoundary

###  delete
DELETE http://localhost:8081/api/v1/attach/delete/2db39b7e-f95c-436c-86cc-093527ee93a3









