




### login
POST localhost:8081/api/v1/auth
Content-Type:  application/json

{
  "email": "alish@mail.ru",
  "password": "123456"
}

### registratoin
POST localhost:8081/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "Kamol",
  "surname": "Nematov",
  "email": "kamol@mail.ru",
  "phone": "123",
  "password": "123456",
  "role": "MODERATOR"

}

