




### login
POST localhost:8081/api/v1/auth
Content-Type:  application/json

{
  "email": "eshmat@mail.ru",
  "password": "555"
}

### registratoin
POST localhost:8081/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "Admin",
  "surname": "Adminov",
  "email": "admin@mail.ru",
  "phone": "112233",
  "password": "555"
}

