### Create profle
POST localhost:8081/api/v1/profile
Content-Type:  application/json

{
  "name": "Alish",
  "surname": "Aliyev",
  "email": "alish@mail.ru",
  "phone": "1213",
  "password": "123456",
  "role": "MODERATOR"
}