### Create profle
POST localhost:8081/api/v1/profile
Content-Type:  application/json

{
  "name": "Jasur",
  "surname": "Jumanov",
  "email": "jasur@mail.ru",
  "phone": "123456789",
  "password": "332244",
  "role": "MODERATOR"
}



### update profile
POST localhost:8081/api/v1/profile/update1/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNDgzOTQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzQ3OTQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.7RteHcbwof45iNHtjhanE8o_-ZPUZvT5XIhKA_tAEAiLVcCDa0AWs8t6_2sSX3ISHZq2P2scyLMrmkBZD1cnNw
Content-Type:  application/json

{
"name": "Sobir",
"surname": "Sobirov",
"email": "sobir@mail.ru",
"phone": "2211",
"password": "1111121111",
"role": "PUBLISHER"
}



### delete
DELETE localhost:8081/api/v1/profile/delete/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNDgzOTQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzQ3OTQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.7RteHcbwof45iNHtjhanE8o_-ZPUZvT5XIhKA_tAEAiLVcCDa0AWs8t6_2sSX3ISHZq2P2scyLMrmkBZD1cnNw
Content-Type: application/json

### get profleList
GET localhost:8081/api/v1/profile/getAll?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNDgzOTQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzQ3OTQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.7RteHcbwof45iNHtjhanE8o_-ZPUZvT5XIhKA_tAEAiLVcCDa0AWs8t6_2sSX3ISHZq2P2scyLMrmkBZD1cnNw
Content-Type:  application/json