
### category create
POST localhost:8081/api/v1/region
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNTA1NTksImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzY5NTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1nCgPtuifWhtPWMa4UJWgw2G1leTafx7Cq5fstNeTwoC7nE8U6irOpULqJ-VhhDwrWfL-uq4qfHPqp34batZNA
Content-Type: application/json

{
  "nameUZ": "uz",
  "nameEN": "en",
  "nameRU": "ru"
}




### region update
PUT localhost:8081/api/v1/region/update/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNTA1NTksImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzY5NTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1nCgPtuifWhtPWMa4UJWgw2G1leTafx7Cq5fstNeTwoC7nE8U6irOpULqJ-VhhDwrWfL-uq4qfHPqp34batZNA
Content-Type: application/json

{
  "nameUZ": "UZ",
  "nameEN": "EN",
  "nameRU": "RU"
}


### category update
DELETE localhost:8081/api/v1/region/delete/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNTA1NTksImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzY5NTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1nCgPtuifWhtPWMa4UJWgw2G1leTafx7Cq5fstNeTwoC7nE8U6irOpULqJ-VhhDwrWfL-uq4qfHPqp34batZNA
Content-Type: application/json


### category getAll
PUT localhost:8081/api/v1/region/getAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIyNTA1NTksImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIzMzY5NTksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1nCgPtuifWhtPWMa4UJWgw2G1leTafx7Cq5fstNeTwoC7nE8U6irOpULqJ-VhhDwrWfL-uq4qfHPqp34batZNA
Content-Type: application/json